# Generated by Django 4.0.6 on 2022-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Nombre_usuario', models.CharField(max_length=40)),
                ('Genero', models.CharField(max_length=40)),
                ('Fecha_nacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Peso', models.IntegerField()),
                ('Edad', models.IntegerField()),
                ('Estatura', models.IntegerField()),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
