# Generated by Django 4.0.6 on 2022-08-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='Nombre_usuario',
        ),
    ]
