# Generated by Django 4.0.6 on 2022-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0002_remove_usuario_apellido_remove_usuario_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
