# Generated by Django 4.0.6 on 2022-09-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0003_deportes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Password',
            new_name='calorias',
        ),
    ]
