# Generated by Django 4.0.6 on 2022-08-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0003_registro_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
    ]
