# Generated by Django 4.0.6 on 2022-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0004_rename_password_registro_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='calorias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
