# Generated by Django 4.0.6 on 2022-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fit', '0004_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('peso', models.IntegerField()),
                ('estatura', models.IntegerField()),
                ('ciudad', models.CharField(max_length=40)),
            ],
        ),
    ]
