# Generated by Django 4.0.6 on 2022-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0005_alter_registro_calorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportes',
            name='Tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deportes',
            name='calorias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
