# Generated by Django 4.0.6 on 2022-08-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='estatura',
            new_name='edad',
        ),
    ]
