# Generated by Django 4.0.6 on 2022-09-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0006_deportes_tiempo_deportes_calorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportes',
            old_name='calorias',
            new_name='calorias_deporte',
        ),
    ]
