# Generated by Django 4.0.6 on 2022-08-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0006_rename_estatura_registro_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='calorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kal', models.IntegerField(max_length=30)),
            ],
        ),
    ]
