# Generated by Django 4.0.6 on 2022-09-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0007_rename_calorias_deportes_calorias_deporte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deportes',
            new_name='Deporte',
        ),
    ]
