# Generated by Django 4.0.6 on 2022-09-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0008_rename_deportes_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='Deporte',
            field=models.CharField(choices=[('Ciclismo', 'Ciclismo'), ('Natacion', 'Natacion'), ('Correr', 'Correr'), ('Gimnasio', 'Gimnasio'), ('Crossfit', 'Crossfit')], max_length=20),
        ),
    ]
