# Generated by Django 4.0.6 on 2022-09-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0010_alter_deporte_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='Deporte',
            field=models.CharField(choices=[('01', 'Ciclismo'), ('02', 'Natacion'), ('03', 'Correr'), ('04', 'Gimnasio'), ('05', 'Crossfit')], max_length=20),
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dificultad', models.CharField(choices=[('p', 'Principiante'), ('i', 'Intermedio'), ('a', 'Avanzado')], max_length=20)),
                ('Descripcion', models.TextField(max_length=100)),
                ('Puntos', models.CharField(choices=[('Principiante', '5'), ('Principiante', '10'), ('Intermedio', '15'), ('Intermedio', '20'), ('Avanzado', '25'), ('Intermedio', '30')], max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.registro')),
            ],
        ),
    ]
