# Generated by Django 4.0.6 on 2022-09-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0012_alter_deporte_deporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='eleccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metas',
            name='Dificultad',
            field=models.CharField(choices=[('1', 'Principiante'), ('2', 'Principiante'), ('3', 'Intermedio'), ('4', 'Intermedio'), ('5', 'Avanzado'), ('6', 'Avanzado')], max_length=20),
        ),
    ]
