# Generated by Django 4.0.6 on 2022-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0013_metas_eleccion_alter_metas_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='eleccion',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
