# Generated by Django 4.0.6 on 2022-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0015_alter_deporte_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='Deporte',
            field=models.CharField(choices=[('ci', 'Ciclismo'), ('na', 'Natacion'), ('co', 'Correr'), ('gi', 'Gimnasio'), ('cr', 'Crossfit')], max_length=20),
        ),
    ]
