# Generated by Django 4.0.6 on 2022-09-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0018_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.registro'),
        ),
    ]
