# Generated by Django 4.0.6 on 2022-09-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0020_remove_comida_nombre_remove_comida_dientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='Azucar',
            field=models.CharField(choices=[('Porcion', '<10 gramos'), ('2_Porciones', '<50 gramos'), ('3_porciones', '<100 gramos'), ('4_porciones', '<200 gramos'), ('5_porciones', '>300gramos')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comida',
            name='Carbohidratos',
            field=models.CharField(choices=[('Porcion', '100 gramos'), ('2_Porciones', '200 gramos'), ('3_porciones', '300 gramos'), ('+3_porciones', '>300 gramos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Proteina',
            field=models.CharField(choices=[('Porcion', '<100 gramos'), ('2_Porcione', '<150 gramos'), ('3_porcione', '<200 gramos'), ('4_porcione', '<250 gramos'), ('5_porcione', '>300gramos')], max_length=100),
        ),
    ]
