# Generated by Django 4.0.6 on 2022-10-17 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0022_deporte_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bebida', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('calorias_Bedida', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fit.registro')),
            ],
        ),
    ]
