# Generated by Django 4.0.6 on 2022-10-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0023_bedidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedidas',
            old_name='Bebida',
            new_name='Bedida',
        ),
    ]
