# Generated by Django 4.0.6 on 2022-10-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0024_rename_bebida_bedidas_bedida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedidas',
            old_name='Bedida',
            new_name='Bebida',
        ),
    ]
