# Generated by Django 4.0.6 on 2022-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0025_rename_bedida_bedidas_bebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='Fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='Grasas',
            field=models.CharField(choices=[('Porcion', '<10 gramos'), ('2_Porciones', '<20 gramos'), ('3_porciones', '<40 gramos'), ('4_porciones', '<60 gramos')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comida',
            name='calorias_Comida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Azucar',
            field=models.CharField(choices=[('Porcion', '<10 gramos'), ('2_Porciones', '<20 gramos'), ('3_porciones', '<40 gramos'), ('4_porciones', '<60 gramos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Carbohidratos',
            field=models.CharField(choices=[('Porcion', '25 gramos'), ('2_Porciones', '50 gramos'), ('3_porciones', '100 gramos'), ('+3_porciones', '150 gramos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comida',
            name='Proteina',
            field=models.CharField(choices=[('Porcion', '<100 gramos'), ('2_Porcione', '<25 gramos'), ('3_porcione', '<50 gramos'), ('4_porcione', '<100 gramos'), ('5_porcione', '>150 gramos'), ('6_porcione', '>250 gramos'), ('7_porcione', '>350 gramos')], max_length=100),
        ),
    ]
