# Generated by Django 4.0.6 on 2022-11-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0026_comida_fecha_comida_grasas_comida_calorias_comida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='Azucar',
        ),
    ]
