# Generated by Django 4.0.6 on 2022-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fit', '0035_alter_recetas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
